FROM node:20-bookworm
RUN apt-get update && apt-get install -y --no-install-recommends git ca-certificates openjdk-17-jre-headless && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --omit=dev
COPY src ./src
EXPOSE 7072
CMD ["npm","run","start"]
